import 'package:isar/isar.dart';

part 'pet.g.dart'; // auto-generated by build_runner

@collection
class Pet {
  Id id = Isar.autoIncrement;

  late String name;
  late String species;   // 'dog', 'cat', 'bird', etc.
  late String breed;
  late DateTime dateOfBirth;
  String? profilePhotoPath;

  @enumerated
  late PetGender gender;
}

enum PetGender { male, female, unknown }